version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    labels:
      - "type: chore"
  - package-ecosystem: "npm"
    directory: "/e2e/nextjs-app"
    open-pull-requests-limit: 0
    labels:
      - "type: chore"
