# ================================
# project settings
# ================================

settings:
  trigger:
    include: .pipeline/settings/.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push" # branch pipeline when merge request opened
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # default branch pipeline
      when: manual
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # non defult branch pipeline
      when: manual
  allow_failure: true

# ================================
# default
# ================================

test:
  trigger:
    include: .pipeline/library/.gitlab-ci.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline" # multiproject pipeline trigger
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # merge request pipeline
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push" # branch pipeline when merge request opened
      when: never
    - if: $CI_COMMIT_BRANCH

