export declare const InternationalCallingCodeMap: {
    Singapore: string;
    Afghanistan: string;
    Albania: string;
    Algeria: string;
    Andorra: string;
    Angola: string;
    "Antigua and Barbuda": string;
    Argentina: string;
    Armenia: string;
    Aruba: string;
    Australia: string;
    Austria: string;
    Azerbaijan: string;
    Bahamas: string;
    Bahrain: string;
    Bangladesh: string;
    Barbados: string;
    Belarus: string;
    Belgium: string;
    Belize: string;
    Benin: string;
    Bhutan: string;
    Bolivia: string;
    "Bosnia and Herzegovina": string;
    Botswana: string;
    Brazil: string;
    "British Indian Ocean Territory": string;
    Brunei: string;
    Bulgaria: string;
    "Burkina Faso": string;
    Burundi: string;
    Cambodia: string;
    Cameroon: string;
    Canada: string;
    "Cape Verde": string;
    "Caribbean Netherlands": string;
    "Central African Republic": string;
    Chad: string;
    Chile: string;
    China: string;
    Colombia: string;
    Comoros: string;
    Congo: string;
    "Costa Rica": string;
    "C\u00F4te d\u2019Ivoire": string;
    Croatia: string;
    Cuba: string;
    Curaçao: string;
    Cyprus: string;
    "Czech Republic": string;
    Denmark: string;
    Djibouti: string;
    Dominica: string;
    "Dominican Republic": string;
    Ecuador: string;
    Egypt: string;
    "El Salvador": string;
    "Equatorial Guinea": string;
    Eritrea: string;
    Estonia: string;
    Ethiopia: string;
    Fiji: string;
    Finland: string;
    France: string;
    "French Guiana": string;
    "French Polynesia": string;
    Gabon: string;
    Gambia: string;
    Georgia: string;
    Germany: string;
    Ghana: string;
    Greece: string;
    Grenada: string;
    Guadeloupe: string;
    Guam: string;
    Guatemala: string;
    Guinea: string;
    "Guinea-Bissau": string;
    Guyana: string;
    Haiti: string;
    Honduras: string;
    "Hong Kong": string;
    Hungary: string;
    Iceland: string;
    India: string;
    Indonesia: string;
    Iran: string;
    Iraq: string;
    Ireland: string;
    Israel: string;
    Italy: string;
    Jamaica: string;
    Japan: string;
    Jordan: string;
    Kazakhstan: string;
    Kenya: string;
    Kiribati: string;
    Kosovo: string;
    Kuwait: string;
    Kyrgyzstan: string;
    Laos: string;
    Latvia: string;
    Lebanon: string;
    Lesotho: string;
    Liberia: string;
    Libya: string;
    Liechtenstein: string;
    Lithuania: string;
    Luxembourg: string;
    Macau: string;
    Macedonia: string;
    Madagascar: string;
    Malawi: string;
    Malaysia: string;
    Maldives: string;
    Mali: string;
    Malta: string;
    "Marshall Islands": string;
    Martinique: string;
    Mauritania: string;
    Mauritius: string;
    Mexico: string;
    Micronesia: string;
    Moldova: string;
    Monaco: string;
    Mongolia: string;
    Montenegro: string;
    Morocco: string;
    Mozambique: string;
    Myanmar: string;
    Namibia: string;
    Nauru: string;
    Nepal: string;
    Netherlands: string;
    "New Caledonia": string;
    "New Zealand": string;
    Nicaragua: string;
    Niger: string;
    Nigeria: string;
    "North Korea": string;
    Norway: string;
    Oman: string;
    Pakistan: string;
    Palau: string;
    Palestine: string;
    Panama: string;
    "Papua New Guinea": string;
    Paraguay: string;
    Peru: string;
    Philippines: string;
    Poland: string;
    Portugal: string;
    "Puerto Rico": string;
    Qatar: string;
    Réunion: string;
    Romania: string;
    Russia: string;
    Rwanda: string;
    "Saint Kitts and Nevis": string;
    "Saint Lucia": string;
    "Saint Vincent and the Grenadines": string;
    Samoa: string;
    "San Marino": string;
    "S\u00E3o Tom\u00E9 and Pr\u00EDncipe": string;
    "Saudi Arabia": string;
    Senegal: string;
    Serbia: string;
    Seychelles: string;
    "Sierra Leone": string;
    Slovakia: string;
    Slovenia: string;
    "Solomon Islands": string;
    Somalia: string;
    "South Africa": string;
    "South Korea": string;
    "South Sudan": string;
    Spain: string;
    "Sri Lanka": string;
    Sudan: string;
    Suriname: string;
    Swaziland: string;
    Sweden: string;
    Switzerland: string;
    Syria: string;
    Taiwan: string;
    Tajikistan: string;
    Tanzania: string;
    Thailand: string;
    "Timor-Leste": string;
    Togo: string;
    Tonga: string;
    "Trinidad and Tobago": string;
    Tunisia: string;
    Turkey: string;
    Turkmenistan: string;
    Tuvalu: string;
    Uganda: string;
    Ukraine: string;
    "United Arab Emirates": string;
    "United Kingdom": string;
    "United States": string;
    Uruguay: string;
    Uzbekistan: string;
    Vanuatu: string;
    "Vatican City": string;
    Venezuela: string;
    Vietnam: string;
    Yemen: string;
    Zambia: string;
    Zimbabwe: string;
};
export declare const getCountries: () => string[];
export declare const getPrefix: (country: string) => string;
export declare const getCountryFromPrefix: (prefix: string) => string | undefined;
