name: Trigger GitLab CI Pipeline

on:
  push:
    branches:
      - MOL-12712

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl --request POST \
            --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipeline"

