name: Trigger GitLab CI Pipeline

on:
  push:
    branches:
      - MOL-12712

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: 19225
        run: |
          curl --request POST \
            --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://sgts.gitlab-dedicated.com/api/v4/projects/$GITLAB_PROJECT_ID/pipeline"

